### ISSUE TITLE
 Translation assistance

### ISSUE THREAD

**Issue by YarTom** [JustArthur/ColorCraft#1]
Hello, developer of the ColorCraft resource pack, I just want to ask how you translate the resource pack into different languages, does this happen automatically using a program you wrote, or (hardly) do you manually write each line?
I can also offer free assistance in translating the resource pack into Russian and (Maybe) Ukrainian and Belarusian 

My page on modrinth: https://modrinth.com/user/YarTom

Sorry for the possible poor English, I am writing through a translator, although as I understand your native language is not English

You can contact me via discord @yartom

**Comment by JustArthur** [comment]
Hello, to translate my pack into different languages, I use the language files created by the mod or the game by default, which I find in the lang folder. The default is very often the en_us.json. Since I am French, I translate it myself into French, using DeepL.

Yes, I check each line of the file to see which ones are important, and I manually write the lines. If the translation into French doesn't exist, I take the opportunity to create one.

To apply the colors, I use the color codes from the game, which can be found on this site: https://minecraftitemids.com/color-codes, using the "§" codes.

Next, to create your translation, you just need to create a fork on GitHub. Once you're done, simply submit a pull request to my main branch. I don't speak your languages, so I'll leave the translation to you.
